name: Run Unit Tests

on:
  schedule:
    - cron: '0 7 * * 1'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13.0' 

    - name: Create and activate virtual environment
      run: |
        python -m venv venv  # Create virtual environment
        source venv/bin/activate  # Activate virtual environment
        python -m pip install --upgrade pip  # Upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt
        pip install pytest

    - name: Run Pytest and produce JUnit XML
      run: |
          source venv/bin/activate
          pytest --junitxml=test-results.xml
          
    - name: Upload test results artifact
      uses: actions/upload-artifact@v4
      with:
          name: pytest-results
          path: test-results.xml

    - name: Annotate test failures in GitHub UI
      if: failure()  # Only run if tests fail
      uses: mikepenz/action-junit-report@v4
      with:
        report_paths: "test-results.xml"